apiVersion: v1
kind: Service
metadata:
  namespace: sc-namespace
  name: smart-campus-be-service
spec:
  type: ClusterIP
  selector:
    app: sc-backend
  ports:
    - port: 5000
      targetPort: 5000