apiVersion: v1
kind: Secret
metadata:
  name: smart-campus-secret-example
type: Opaque
stringData:
  MONGO_URI: "<your mongo uri>"
  MONGO_USER: "<your mongo user>"
  MONGO_PASS: "<your mongo password>"
  JWT_SECRET: "<your jwt secret>"
  CLOUD_KEY: "<your cloud key>"       # we used cloudinary in this project it may vary if you use other cloud
  CLOUD_SECRET: "<your cloud secret>"
  EMAIL_USER: "<your email user>"
  EMAIL_PASS: "<your email password>"
  TWILIO_ACCOUNT_SID: "<your twilio account sid>"
  TWILIO_AUTH_TOKEN: "<your twilio account auth token>"
  TWILIO_PHONE: "<your twilio phone number>"