name: smart-campus-asssistant-ci
run-name: CI Pipeline

on: [push]

env:
  REGISTRY: ghcr.io
  FE_IMAGE_NAME: ${{ github.repository }}-frontend
  BE_IMAGE_NAME: ${{ github.repository }}-backend
jobs:
    CI-Pipeline:
        runs-on: ubuntu-latest

        permissions:
          contents: read
          packages: write

        steps:
          # Checkout Code to Runner
            - name: Check Out Repository Code
              uses: actions/checkout@v6
            - run: echo "The Repository ${{ github.repository }} has been Cloned to the runner!"

          # Login into GHCR
            - name: Login to GHCR
              uses: docker/login-action@v4
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          # Build FE Docker Image and keep it loaded for Vulnerability Scanning USING Hardcoded tag for scanning
            - name: Build Docker Frontend Image
              id: frontend-build
              uses: docker/build-push-action@v4
              with:
                context: ./frontend
                push: false
                load: true
                tags: local/frontend:scan

          # Scan Frontend Docker Image for HIGH / CRITICAL Vulnerabilities Fail if HIGH or CRITICAL Vuln found else push
            - name: Scan Frontend Image
              id: frontend-image-trivy-scan
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: local/frontend:scan
                severity: HIGH,CRITICAL
                exit-code: '1'

          # Extract Metadata for FE
            - name: Extract Metadata for Frontend Image
              id: fe-metadata
              uses: docker/metadata-action@v6
              with:
                images: ${{ env.REGISTRY }}/${{ env.FE_IMAGE_NAME }} # Ahh so it will be my ghcr.io/my repo name ??

          # Finally Push to ghcr.io
            - name: Push Frontend Image to ghcr.io
              uses: docker/build-push-action@v4
              with:
                context: ./frontend
                push: true
                tags: ${{ steps.fe-metadata.outputs.tags }}
                labels: ${{ steps.fe-metadata.outputs.labels }}

          # Build BE Docker Image  and keep it Loaded for Vulnerability Scanning USING Hardcoded tag for scanning
            - name: Build and Push Docker Backend Image
              id: backend-push
              uses: docker/build-push-action@v4
              with:
                context: ./backend
                push: false
                load: true
                tags: local/backend:scan

          # Scan Backend Docker Image for HIGH / CRITICAL Vulnerabilities Fail if HIGH or CRITICAL Vuln found else push
            - name: Scan Backend Image
              id: backend-image-trivy-scan
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: local/backend:scan
                severity: HIGH,CRITICAL
                exit-code: '1'
                trivyignores: ./backend/.trivyignore

          # Extract Metadata for BE
            - name: Extract Metadata for Backend Image
              id: be-metadata
              uses: docker/metadata-action@v6
              with:
                images: ${{ env.REGISTRY }}/${{ env.BE_IMAGE_NAME }} # Ahh so it will be my ghcr.io/my repo name ??

          # Finally Push to ghcr.io
            - name: Push Backend Image to ghcr.io
              uses: docker/build-push-action@v4
              with:
                context: ./backend
                push: true
                tags: ${{ steps.be-metadata.outputs.tags }}
                labels: ${{ steps.be-metadata.outputs.labels }}