name: github-actions-demo
run-name: ${{ github.actor }} is testing out Github Actions!!!

on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repository Code
              uses: actions/checkout@v6
            - run: echo "The Repository ${{ github.repository }} has been Cloned to the runner!"

            - name: Build The Docker Image
              run: docker build -t smart-campus-backend:v1 -f ./backend/Dockerfile ./backend

            - name: Build The Frontend Docker Image
              run: docker build -t smart-campus-frontend:v1 -f ./frontend/Dockerfile ./frontend